### ISSUE TITLE
No indication of staff status on the front end for admin users

### ISSUE THREAD

**Issue by enigmathix** [galacticpuzzlehunt/gph-site#18]
A common error happens when manage.py createsuperuser is used to create an admin user instead of using the manage.py loaddata sample.yaml file, or when Toggle Testuser is clicked on the home page: when the staff status is unset, an admin user can't visit the puzzle page they create and gets this error:

Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/puzzles
Raised by:	puzzles.views.puzzles

It would be good to have a clear indication on the front end that the current admin user has a staff status or not, there is currently none and it's easy to spend a long time trying to figure out where this error comes from.

This code would achieve that in puzzles/templates/base.html after the team name:
```
            {% if team.is_prerelease_testsolver %}
            <span class="current-stat" title="Beta Tester">&beta;</span>
            {% endif %}

```

**Comment by cesium12** [comment]
Thanks for reporting! We may add this when we next start working on the codebase (or if you'd like to put together a PR, we can pull it in sooner).
